language: c

os: linux

addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8

env:
  global:
    - RACKET_DIR=~/racket
    - RACKET_VERSION="7.0"
    - Z3_VERSION="4.5.0"
    - Z3_DISTRIB="z3-4.5.0-x64-ubuntu-14.04"
    - CC="gcc-4.8"
    - CXX="g++-4.8"

# Caching for stack
# See https://docs.haskellstack.org/en/stable/travis_ci/
cache:
  directories:
  - $HOME/.stack

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - curl -L -O https://github.com/Z3Prover/z3/releases/download/z3-${Z3_VERSION}/${Z3_DISTRIB}.zip
  - unzip ${Z3_DISTRIB}.zip
  - export PATH="${RACKET_DIR}/bin:${PWD}/${Z3_DISTRIB}/bin:${PATH}"
  - raco pkg install --auto rosette
  - sudo apt-get install -qq python3
# Download and unpack Stack
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  - make test
